apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: user-service
  annotations:
    instrumentation.opentelemetry.io/inject-java: my-apps/my-instrumentation
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{"instrumentation.opentelemetry.io/inject-java":"my-apps/my-instrumentation"},"labels":{"apis.apps.tanzu.vmware.com/register-api":"true","app.kubernetes.io/part-of":"user-service","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"},"name":"user-service","namespace":"my-apps"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17.*"}]},"env":[{"name":"spring.cloud.config.uri","value":"http://config-server.my-apps.svc.cluster.local"},{"name":"EUREKA_URL","value":"http://discovery-server.my-apps.svc.cluster.local/eureka"},{"name":"OTEL_RESOURCE_ATTRIBUTES","value":"application=bankingApp"},{"name":"spring.jpa.database-platform","value":"org.hibernate.dialect.PostgreSQLDialect"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/maxScale":"10","autoscaling.knative.dev/minScale":"1","autoscaling.knative.dev/scaleDownDelay":"10m"}},{"name":"api_descriptor","value":{"description":"A set of API endpoints to manage the resources within the user-service App.","location":{"path":"/v3/api-docs"},"owner":"bank-team-a","system":"tanzu-banking-system","type":"openapi"}},{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/language":"java","apps.tanzu.vmware.com/pipeline":"test"}},{"name":"scanning_source_policy","value":"scan-policy"},{"name":"scanning_image_policy","value":"scan-policy"}],"serviceClaims":[{"name":"postgres-user-db","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ClassClaim","name":"user-database"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/MoSehsah/bank-demo"},"subPath":"user-service"}}}
    autoscaling.knative.dev/maxScale: "10"
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/scaleDownDelay: 10m
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: user-service
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: user-service
spec:
  type: openapi
  description: A set of API endpoints to manage the resources within the user-service App.
  system: tanzu-banking-system
  owner: bank-team-a
  location:
    path: /v3/api-docs
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: user-service

