apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: springboot-maven
  labels:
    app.kubernetes.io/part-of: springboot-maven
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: external-deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: springboot-maven
    carto.run/workload-namespace: my-apps
spec:
  params:
  - name: gitops_ssh_secret
    value: git-secret
  source:
    git:
      url: https://github.com/robertocolella/tap-gitops-config.git
      ref:
        branch: production
    subPath: config/my-apps/springboot-maven

